// Project Actions
export const REQUEST_PROJECTS = "REQUEST_PROJECTS";
export const RECEIVE_PROJECTS_SUCCESS = "RECEIVE_PROJECTS_SUCCESS";
export const RECEIVE_PROJECTS_FAILURE = "RECEIVE_PROJECTS_FAILURE";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED";

// Authentication Actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAILED = "USER_CREATE_FAILED";


// File Actions
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const UPDATE_FILE_SUCCESS = "UPDATE_FILE_SUCCESS";
export const GET_FILE_SUCCESS = "GET_FILE_SUCCESS";
export const FILE_OPERATION_FAILURE = "FILE_OPERATION_FAILURE";